# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET http://localhost:8000/tracks?key=user

###
GET http://localhost:8000/track?key=test&track_id=test_2024-10-19T22-14-08&format=json

###
GET https://backtrack.cliftbar.site/track?key=test&track_id=test_2024-10-19T23-30-49&format=json

###
GET http://backtrack.cliftbar.site/test/track/test_2024-10-19T23-30-49/json